### ISSUE TITLE
Feature request for putty

### ISSUE THREAD

**Issue by isindir** [cristianst85/QuickConnectPlugin#2] opened 2016-03-14 19:41 UTC
Hi Cristian,

Putty by default loads "Default settings" to start a session, it would be extremely handy to be able to configure ability to load different stored session configuration when starting session. All sessions in putty are being kept in registry, so names are easily available. putty binary accepts `-load "session name"` syntax to load stored session. It could be another "matching" field in QuickConnect configuration if putty binary is available.
**Reasoning**: some of the features of stored session may differ from server to server, for example tunneling, colors of the shell, keyboard/mouse/font settings.

Another suggestion is to add at least following keywords for putty session startup:
ssh
telnet
As putty supports these protocols using command line options:
putty.exe [-load "session_name"] [-ssh | -telnet | -rlogin | -raw] [user@]host

Thanks,
Eriks

**Comment by cristianst85** [comment] 2016-03-16 20:13
One way to do this, as you mentioned already, is to have another field mapping where to store additional arguments for Putty (except username, password and host address) that will override current/default behavior.

Some examples:
`-load "session"` launches `putty.exe -load "session" -l username -pw password`
`-telnet` launches `putty.exe -telnet username@host -pw password`
[empty or missing] launches `putty.exe -ssh username@host -pw password`

Please let me know if I've understood this use case correctly.

**Comment by isindir** [comment] 2016-03-16 21:43
Let me try to explain better. If ssh client is set and is putty , and regex pattern is set in an extra field: than within "open terminal" menu item event - plugin is searching for this text in a a list of putty session names, which can be loaded from registry. First matching name should be used when launching putty via extra flag "-load". If no session name matching, then load flag not used and "default settings" profile will be loaded. Pattern can be given in a text field somesing like:
profile:"<profile name>" or load:"<profile name>", so that it can be combined with other text and still be found..
This is more complex than matchig given list of known words.

For the second part, ssh can be added to the list of distros (putty uses default -ssh flag). Extra list containing telnet word only added, if matched - -telnet flag is used instead of -ssh. I haven't checked if rdp pattern is listed for windows, if not I think it would make sense to add it as well.

Best Regards.

**Comment by cristianst85** [comment] 2016-04-13 18:07
A new version with the requested feature is available for download [here](https://github.com/cristianst85/QuickConnectPlugin/releases/tag/0.3.0-rc.1).

Same field can be used for specifying both the `Connection Method` and the `Additional 
Options` (only for PuTTY).

The syntax for `Additional Options` is: `[{ssh|telnet}|<os_type>;]session:"<regex_pattern>"` 

Examples:
- session:"My Session"
- ssh;session:MySession

**Comment by cristianst85** [comment] 2016-04-26 15:56
@isindir, have you had the chance to test this release?

**Comment by isindir** [comment] 2016-04-26 16:24
Hi Cristian, apologies for late response.

2 issues noticed:
- when plugin loads it does not check if it is already loaded in keepass. I had an old version of plugin, and unarchieved new version in keepass folder - which produced 3 copies of plugin in total (2 in subfolders). All copies produced menu items in _Main Menu:Tools_ and produced menu items in keepass entry _popup menu_.
- I'm using names for sessions like: "`%cygterm @ yellow/dark ! blue`" . Correct session was not loaded, when I have used following Title for an entry:
  `Jenkins ssh;session:"%cygterm @ yellow/dark ! blue"`
  and just an IP address in URL entry.

I have following settings:

```
General:
  Enable +
  Compatible mode: +
Map Fields:
  Host address from: URL
  Connection method from: Titile
  Additional options from: Empty
```

Best Regards

**Comment by cristianst85** [comment] 2016-04-26 17:03
- Regarding the first issue in not really a plugin issue, but that's how KeePass loads the plugins in generally. 
- Secondly, you need to map Additional options (QuickConnect -> Options -> Map Fields) to the field containing the session name (see the pic below). In your case that would be the `Title` field.

![quickconnectplugin-additional-options-mapping](https://cloud.githubusercontent.com/assets/12585988/14827098/6fde9404-0be9-11e6-8647-9381e5a567f8.png)

**Comment by isindir** [comment] 2016-05-17 14:34
@cristianst85 ,

I have done a little bit more testing today:
- QuickConnect Options:

```
Host address: URL
Connection method from: Title
Additional options from: putty_session
```
- Entry in KeePass is configured as follows:

```
Title: ssh
URL: 192.168.1.100
Advanced->String Fields->putty_session :    session:"%cygterm @ yellow/dark_blue"
```
- Putty configuration contains exact this session name configured as it is set in KeePass and colors are not picked up from this session, when launching putty session. In my case there is only one session name configured which does contain `"dark_blue"`, even if I configure KeePass entry `"putty_session" : "dark_blue"` or `".*dark_blue.*"` it still does not pick up this session settings. If I set it to `"*dark_blue*"` - exception is raised.
- On the other side if I create plain new session just to a server (no tunnels or proxies as an example) with no special chars in it's name - only then it picks session settings.

Best Regards

**Comment by cristianst85** [comment] 2016-05-25 15:01
@isindir,

it should work now with the latest [release](https://github.com/cristianst85/QuickConnectPlugin/releases/tag/0.3.0-rc.3). PuTTY stores special chars escaped in Windows Registry.

Raising an exception when using `"*dark_blue*"` is the expected behavior because that is not a valid regex expression (instead one should use `".*dark_blue.*"` for matching all occurrences that contains `dark_blue` string).

**Comment by isindir** [comment] 2016-05-26 10:46
@cristianst85 ,

looks funny, it now picks correct session, but may not connect via ssh: putty window stays blank.

I have tried to launch it from cmd, by getting exact command from powershell, like so:
`Get-WmiObject Win32_Process -Filter "name = 'putty.exe'" | select CommandLine`

Getting following result:

```
CommandLine
-----------
"C:\Program Files (x86)\PuTTY\putty.exe"  -load "%template @ yellow/red" -ssh qqq@192.168.1.100 -pw "password here"
```

Trying to launch it from cmd gives me same result as from Keepass , looks like some of the settings in putty session may override the behaviour of -ssh user@host -pw "password". I have to do a little bit more testing for better understanding.

**Comment by isindir** [comment] 2016-06-25 05:32
Lost ability to test - do not have MS Windows box available

**Comment by cristianst85** [comment] 2016-07-03 15:47
I'll close this for now, but feel free to reopen if you consider that we can further improve it.

P.S. Thank you for you feedback.

**Closed as completed by cristianst85** 2016-07-03 15:47 UTC
Labels: type: enhancement

**Comment by thipages** [comment] 2017-02-24 14:26
Hi,
I would like to add SSH tunnels informations while logging with putty, in particular using PortForwardings field

What I have done
1. Fill in a new map field in KeePass "PortForwardings" -> "L1234=127.0.0.1:1234"
2. Fill in Quick Connect>Options>Map Fields>Additional options with "PortForwardings"

But it is not working.

 Can you help me?
Thank you

**Comment by wanderleihuttel** [comment] 2017-02-24 14:37
Hello. You can configure a Session on Putty with this configurations and on KeepSafe use the following config:

SSH;session:"Some Session Name"

Best Regards
Wanderlei

**Comment by thipages** [comment] 2017-02-24 14:45
Perfect!

What I have done in details

1. Fill in a new map field in KeePass "session" -> "SSH;session:myPuttySession"
2. Fill in Quick Connect>Options>Map Fields>Additional options with "session"

Thank you for your quick answer!
